version: "3.8"
name: ${PROJECT_NAME}
services:
  cms:
    container_name: ${PROJECT_NAME}-cms
    image: directus/directus:10.8.3
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}

      # Uncomment to connect from local to DO else SQLite will be used
      # DB_CLIENT: ${DB_CLIENT}
      # DB_HOST: ${DB_HOST}
      # DB_PORT: ${DB_PORT}
      # DB_DATABASE: ${DB_DATABASE}
      # DB_USER: ${DB_USER}
      # DB_PASSWORD: ${DB_PASSWORD}
      # DB_SSL: ${DB_SSL}
      # DB_SSL__CA: ${DB_SSL__CA}
      # NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      EXTENSIONS_AUTO_RELOAD: "true"
    ports:
      - 8010:8055
    volumes:
      - share:/directus/extensions
    labels:
      - traefik.http.routers.${PROJECT_NAME}-cms.rule=Host(`cms.3int.uk`)

  web:
    container_name: ${PROJECT_NAME}-web
    image: web3int:dev
    depends_on:
      - cms
    # environment:
    # LOCAL_HOST: http://localhost:8011
    #   MONGO_URL: ${MONGO_URL}
    #   RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
    #   RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
    # NODE_OPTIONS: ${NODE_OPTIONS}
    ports:
      - 8011:3000
    command: sleep 3600 &
    # volumes:
    #   - share:/app/cms:ro
    labels:
      - traefik.http.routers.${PROJECT_NAME}-web.rule=Host(`3int.uk`)
