version: "3.8"
name: ${PROJECT_NAME}
services:
  cms:
    container_name: ${PROJECT_NAME}-cms
    image: directus/directus:10.10.2
    restart: always
    environment:
      PROJECT_KEY: ${PROJECT_KEY}

      KEY: ${CMS_KEY}
      SECRET: ${CMS_SECRET}

      PUBLIC_URL: https://${CMS_DOMAIN}

      WEB_DOCKER_URL: ${WEB_DOCKER_URL}
      WEB_PUBLIC_URL: https://${WEB_DOMAIN}

      STORAGE_LOCATIONS: digitalocean
      STORAGE_DIGITALOCEAN_DRIVER: s3
      STORAGE_DIGITALOCEAN_KEY: ${DO_SPACES_B1_KEY}
      STORAGE_DIGITALOCEAN_SECRET: ${DO_SPACES_B1_SECRET}
      STORAGE_DIGITALOCEAN_ENDPOINT: ${DO_SPACES_B1_ENDPOINT}
      STORAGE_DIGITALOCEAN_BUCKET: ${DO_SPACES_B1_BUCKET}
      STORAGE_DIGITALOCEAN_REGION: ${DO_SPACES_B1_REGION}

      ADMIN_EMAIL: ${CMS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${CMS_ADMIN_PASSWORD}

      ZEPTOMAIL_URL: ${ZEPTOMAIL_URL}
      ZEPTOMAIL_TOKEN: ${ZEPTOMAIL_TOKEN}

      REVOLUT_MERCHANT_HOST: ${REVOLUT_MERCHANT_HOST}
      REVOLUT_MERCHANT_SECRET: ${REVOLUT_MERCHANT_SECRET}

      FLOWS_ENV_ALLOW_LIST: "PROJECT_KEY,WEB_DOCKER_URL,WEB_PUBLIC_URL"

      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: https://${WEB_DOMAIN}

      # EXTENSIONS_AUTO_RELOAD: "true"
    networks:
      - traefik_proxy
    volumes:
      - ${WORKDIR}/persist/database:/directus/database
      - ${WORKDIR}/extensions:/directus/extensions
    labels:
      - traefik.http.routers.${PROJECT_NAME}-cms.rule=Host(`${CMS_DOMAIN}`)
      - traefik.http.routers.${PROJECT_NAME}-cms.entryPoints=websecure
      - traefik.http.routers.${PROJECT_NAME}-cms.tls.certResolver=web3int

  web:
    container_name: ${PROJECT_NAME}-web
    image: ${DO_CR_IMAGE}
    restart: always
    environment:
      PROJECT_KEY: ${PROJECT_KEY}

      CMS_DOCKER_URL: ${CMS_DOCKER_URL}
      CMS_PUBLIC_URL: ${CMS_PUBLIC_URL}
      CMS_DRAFT_TOKEN: ${CMS_DRAFT_TOKEN}

      WEB_PUBLIC_URL: ${WEB_PUBLIC_URL}

      ZEPTOMAIL_URL: ${ZEPTOMAIL_URL}

      NEXT_PUBLIC__WEB_PUBLIC_URL: ${WEB_PUBLIC_URL}
      NEXT_PUBLIC__STRIPE_PUBLIC_KEY: ${WEB_STRIPE_PUBLIC_KEY}
    depends_on:
      - cms
    networks:
      - traefik_proxy
    labels:
      - traefik.http.routers.${PROJECT_NAME}-web.rule=Host(`${WEB_DOMAIN}`)
      - traefik.http.routers.${PROJECT_NAME}-web.entryPoints=websecure
      - traefik.http.routers.${PROJECT_NAME}-web.tls.certResolver=web3int

networks:
  traefik_proxy:
    external: true
