version: "3.8"
name: ${PROJECT_NAME}
services:
  cms:
    container_name: ${PROJECT_NAME}-cms
    image: directus/directus:10.11.0
    restart: always
    environment:
      PROJECT_KEY: ${PROJECT_KEY}

      KEY: ${CMS_KEY}
      SECRET: ${CMS_SECRET}

      PUBLIC_URL: https://${CMS_DOMAIN}

      WEB_DOCKER_URL: ${WEB_DOCKER_URL}
      WEB_PUBLIC_URL: https://${WEB_DOMAIN}

      STORAGE_LOCATIONS: digitalocean
      STORAGE_DIGITALOCEAN_DRIVER: s3
      STORAGE_DIGITALOCEAN_KEY: ${DO_SPACES_B1_KEY}
      STORAGE_DIGITALOCEAN_SECRET: ${DO_SPACES_B1_SECRET}
      STORAGE_DIGITALOCEAN_ENDPOINT: ${DO_SPACES_B1_ENDPOINT}
      STORAGE_DIGITALOCEAN_BUCKET: ${DO_SPACES_B1_BUCKET}
      STORAGE_DIGITALOCEAN_REGION: ${DO_SPACES_B1_REGION}

      ADMIN_EMAIL: ${CMS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${CMS_ADMIN_PASSWORD}

      ZEPTOMAIL_URL: ${ZEPTOMAIL_URL}
      ZEPTOMAIL_TOKEN: ${ZEPTOMAIL_TOKEN}

      REVOLUT_MERCHANT_HOST: ${REVOLUT_MERCHANT_HOST}
      REVOLUT_MERCHANT_SECRET: ${REVOLUT_MERCHANT_SECRET}

      FLOWS_ENV_ALLOW_LIST: "PROJECT_KEY,WEB_DOCKER_URL,WEB_PUBLIC_URL"

      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: https://${WEB_DOMAIN}

      # EXTENSIONS_AUTO_RELOAD: "true"
    volumes:
      - ./db:/directus/database
