version: "3.8"
name: web-3int
services:
  cms:
    container_name: cms
    build:
      dockerfile: ./cms/.dockerfile
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}

      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      EXTENSIONS_AUTO_RELOAD: "true"

  web:
    container_name: web
    build:
      dockerfile: ./web/.dockerfile
    depends_on:
      - cms
    environment:
      MONGO_URL: ${MONGO_URL}
      RECAPTCHA_SITE_KEY: ${RECAPTCHA_SITE_KEY}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      NODE_OPTIONS: ${NODE_OPTIONS}