FROM node:18.19.0-alpine

RUN apk add --no-cache libc6-compat

ARG MONGO_URL
ARG RECAPTCHA_SITE_KEY
ARG RECAPTCHA_SECRET_KEY

ENV MONGO_URL=$MONGO_URL \
    RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY \
    RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY \
    WEB_HOST=http://web \
    NODE_OPTIONS=--max-old-space-size=512 \
    NEXT_TELEMETRY_DISABLED=1

WORKDIR /app
COPY . .

RUN rm -rf .next .vscode .github
RUN npm ci
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]

# CMD ["sleep", "3600"]