name: My Workflow

on:
  # push:
  #   branches: [main]
  workflow_dispatch:
    inputs:
      option:
        type: choice
        required: true
        options:
          - A
          - B

jobs:
  job1:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.inputs.option == 'A'
    steps:
      - name: Run Job1 tasks
        run: echo "Running Job1 tasks"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: github.event_name == 'push' || (github.event.inputs.option == 'B' && always())
    steps:
      - name: Run Job2 tasks (same as job3)
        run: echo "Running Job2 tasks"
