name: CI/CD

on:
  # Auto trigger
  # push:
  #   branches: [ main ]
  #   paths-ignore:
  #     - '.github/workflows/deployment.yml'

  # Manual trigger
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Trigger job'
        default: 'build and deploy'
        type: choice
        options:
          - 'build and deploy'
          - 'rebuild'
          - 'redeploy'

env:
  SSH_CONN: '${{ secrets.DO_USERNAME }}@${{ secrets.DO_HOST }}'

jobs:

  build_and_push:
    name: Build and push
    if: github.event_name == 'push' || contains(fromJson('["build and deploy", "rebuild"]'), github.event.inputs.manual_trigger )
    uses: ./.github/workflows/build_and_push.yml
    # runs-on: ubuntu-latest
    # steps:
    #   - name: (debug) Build and push
    #     run: echo "Build and push"
    
  and_deploy:
    name: + Deploy
    if: github.event_name == 'push' || github.event.inputs.manual_trigger == 'build and deploy'
    needs: build_and_push
    uses: ./.github/workflows/build_and_push.yml
    # runs-on: ubuntu-latest
    # steps:
    #   - name: (debug) and Deploy
    #     run: echo "and Deploy"

  deploy:
    name: Redeploy
    if: github.event.inputs.manual_trigger == 'redeploy'
    uses: ./.github/workflows/deploy.yml
    # runs-on: ubuntu-latest
    # steps:
    #   - name: (debug) Deploy
    #     run: echo "Deploy"
