name: CI/CD

on:
  # Auto trigger
  # push:
  #   branches: [ main ]
  #   paths-ignore:
  #     - '.github/workflows/deployment.yml'

  # Manual trigger
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: 'Trigger job'
        default: 'build and deploy'
        type: choice
        options:
          - 'build and deploy'
          - 'rebuild'
          - 'redeploy'

env:
  SSH_CONN: '${{ secrets.DO_USERNAME }}@${{ secrets.DO_HOST }}'

jobs:

  build_and_push:
    if: github.event_name == 'push' || contains(fromJson(['build and deploy', 'rebuild']), github.event.inputs.manual_trigger )
    # uses: ./.github/workflows/build_and_push.yml
    steps:
      - name: (debug) Build and push
        run: echo "Build and push"
    
  and_deploy:
    if: github.event_name == 'push' || github.event.inputs.manual_trigger == 'build and deploy'
    needs: build_and_push
    # uses: ./.github/workflows/build_and_push.yml
    steps:
      - name: (debug) and Deploy
        run: echo "and Deploy"

  deploy:
    if: github.event.inputs.manual_trigger == 'redeploy'
    # uses: ./.github/workflows/deploy.yml
    steps:
      - name: (debug) Deploy
        run: echo "Deploy"
