name: CD

# 1
on:
  workflow_dispatch:

# 2
env:
  REG: ${{ secrets.DO_REGISTRY }}
  IMG: ${{ vars.IMAGE_NAME }}
  WORKDIR: '/sources/${{ vars.IMAGE_NAME }}'
  SSH_CONN: '${{ secrets.DO_USERNAME }}@${{ secrets.DO_HOST }}'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval `ssh-agent`
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts
      # - name: Test connection
      #   run: |
      #     ssh ${{ env.SSH_CONN }} 'cd / && ls -l'
      - name: Establish SSH connection
        run: ssh ${{ env.SSH_CONN }}
      - name: Recreate workdir
        run: ssh ${{ env.SSH_CONN }} 'rm -rv ${{ env.WORKDIR }} && mkdir ${{ env.WORKDIR }}'
      - name: Check existence of directory
        run: ssh ${{ env.SSH_CONN }} 'ls -l /sources/'
      - name: Check existence of docker compose file
        run: ls -l
      - name: Transfer docker-compose
        run: scp ./docker-compose.yml ${{ env.SSH_CONN }}:${{ env.WORKDIR }}
      - name: Check existence of file
        run: ssh ${{ env.SSH_CONN }} 'ls -l ${{ env.WORKDIR }}'
      # - name: Copy docker-compose file to VPS
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.DO_HOST }}
      #     username: ${{ secrets.DO_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     source: "docker-compose.yml"
      #     target: ${{ env.WORKDIR }}
      #     rm: true
      # - name: Deploy to Digital Ocean droplet via SSH action
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.DO_HOST }}
      #     username: ${{ secrets.DO_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: |
      #       cd ${{ env.WORKDIR }}
      #       ls -l
