name: CD

# 1
on:
  workflow_dispatch:

# 2
env:
  REG: ${{ secrets.DO_REGISTRY }}
  IMG: ${{ vars.IMAGE_NAME }}
  WORKDIR: '/sources/${{ vars.IMAGE_NAME }}'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: Copy docker-compose file to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: ${{ env.WORKDIR }}
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.WORKDIR }}
            ls -l
